[package]
name        = "cw-extra-types"
description = "Definition and types for the CosmWasm-83 interface"
authors     = [ "Kromsten <s@users.noreply.megarock.labs>" ]
version     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
protos              = { workspace = true }
cosmwasm-schema     = { workspace = true }

cosmwasm-std        = { version = "2.2.2",  optional = true }
secretwasm-std      = { version = "1.1.11", optional = true, package = "secret-cosmwasm-std" }
cosmwasm-std-one    = { version = "1.5.11", optional = true, package = "cosmwasm-std" }
cw-storage-plus-one = { version = "1.2.0", optional = true, package = "cw-storage-plus" }
cw-storage-plus     = { version = "2.0.0", optional = true }


[features]
cosmwasm          =   ["dep:cosmwasm-std",  "dep:cw-storage-plus"]
cosmwasm_1        =   ["dep:cosmwasm-std-one",  "dep:cw-storage-plus-one"]
secretwasm        =   ["dep:secretwasm-std" ]
multi             =   ["registry_multi", "account_multi"]
registry_multi    =   []
account_multi     =   []