[package]
name = "cw82"
authors = [ "Kromsten <s@users.noreply.megarock.labs>" ]
description = "Definition and types for the CosmWasm-82 interface"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
schemars        = { workspace = true }

cw1             = { workspace = true }
cw2             = { workspace = true }
cw22            = { workspace = true }
cw81            = { workspace = true }
cw82-derive     = { path = "./derive", version = "1.2.3" }

[features]
default         = ["cosmwasm_2_1"]
cosmwasm_2_0    = ["cw81/cosmwasm_2_0"]
cosmwasm_2_1    = ["cw81/cosmwasm_2_1"]


[dev-dependencies]
cosmwasm-crypto = "1.5.8"
sha2            = { workspace = true }
k256            = { workspace = true }

ed25519-zebra = "4.0.3"
rand_chacha = "0.3.1"
