[workspace]
members = ["packages/*", "contracts/*"]

# Resolver has to be set explicitely in workspaces, see https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[workspace.package]
version    = "0.1.0"
edition    = "2021"

[workspace.dependencies]
cosmwasm-schema = "1.4.1"
cosmwasm-std = { version = "1.4.1", default-features = false }
cw-storage-plus = "1.1.0"

k256 = { version = "0.13.1", features = ["ecdsa"] }
sha2 = "0.10.8"

cw-utils = "1.0.2"
cw2 = "1.1.1"
cw81 = { version = "0.1.0", path = "packages/cw81" }

thiserror = { version = "1.0" }


[profile.release.package.cw81]
codegen-units = 1
incremental = false


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
