[package]
name        = "cw23-derive"
version     = "0.1.0"
description = "Macros for generating code used by the `cw23` package"
authors     = [ "Kromsten <s@users.noreply.megarock.labs>" ]
edition     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"