[package]
name        = "cw-extra-protos"
description = "Macros for generating code used by the `cw-extra` packages"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }
authors     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"