[package]
name        = "cw83-derive"
description = "Macros for generating code used by the `cw83` package"
authors     = [ "Kromsten <s@noreply.megarock.labs>" ]
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"