[package]
name = "cw83"
description = "Definition and types for the CosmWasm-83 interface"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }
authors     = { workspace = true }


[dependencies]
types           = { workspace = true }
cosmwasm-schema = { workspace = true }


[features]
default         =   ["cosmwasm"]
cosmwasm        =   ["types/cosmwasm"]
cosmwasm_1      =   ["types/cosmwasm_1"]
secretwasm      =   ["types/secretwasm"]
multi           =   ["types/registry_multi"]