[package]
name = "cw81"
authors = [ "Kromsten <s@users.noreply.megarock.labs>" ]
description = "Definition and types for the CosmWasm-81 interface"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw22            = { workspace = true }
cw81-derive     = { path = "./derive", version = "1.2.3" }


[dev-dependencies]
sha2            = { workspace = true }
k256            = { workspace = true }
cosmwasm-crypto = { version = "1.5.8" }

ed25519-zebra = "4.0.3"
rand_chacha = "0.3.1"
